# Generated by Django 6.0.6 on 2026-06-22 08:40

from django.db import migrations


def create_initial_data(apps, schema_editor):
    TeamMember = apps.get_model("dashboard", "TeamMember")
    Announcement = apps.get_model("dashboard", "Announcement")

    for name in ["Riyad", "Nasir", "Shuvo"]:
        TeamMember.objects.get_or_create(name=name)

    Announcement.objects.get_or_create(
        pk=1,
        defaults={
            "message": "Welcome to Team Operation CPMO. Update the shared message and track progress for all members here."
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
